---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-simple-spring-boot-02
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox
          command:
            - sh
            - -c
            - |
              # 通过 initContainer 修改用户和组权限
              chown -R 1001:1001 /assets
              chmod -R 775 /assets
          volumeMounts:
            - name: assets-volume
              mountPath: /assets
      containers:
        - name: demo-app
          image: hello-world-spring-boot
          imagePullPolicy: Never
          env:
            - name: JAVA_OPTS
              value: '-Djava.io.tmpdir=/app/tmp'
          readinessProbe:
            # Readiness probe is used to check if this app is ready to serve traffic.
            httpGet:
              port: 8080
              path: /actuator/health/readiness
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          livenessProbe:
            # Liveness probe is used to check if this app is responding to requests
            # (after it is marked as "ready").
            httpGet:
              port: 8080
              path: /actuator/health/liveness
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          securityContext:
            readOnlyRootFilesystem: false
            runAsUser: 1001
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /app/tmp
              name: tmp-volume
            - mountPath: /assets
              name: assets-volume
      volumes:
        - name: tmp-volume
          # emptyDir: {}
          emptyDir:
            # medium: Memory
            sizeLimit: 200Mi
        - name: assets-volume
          # emptyDir: {}
          emptyDir:
            # medium: Memory
            sizeLimit: 200Mi
      securityContext:
        fsGroup: 1001
