---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-simple-spring-boot-02
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: hello-world-spring-boot
          imagePullPolicy: Never
